name: On Pull Request 1

on:
  workflow_dispatch:
  #pull_request:

jobs:
  test_one:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Try Get-PR
      uses: dkershner6/get-pull-request-action@v1
      id: get-pr
      with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pull-number: 4
          
    - run: echo ${{ fromJSON(steps.get-pr.outputs.pr).title }}
